### ISSUE TITLE
Can't see document edit window

### ISSUE THREAD

**Issue by ivbeg** [alephdata/datadesktop#16]
![изображение](https://user-images.githubusercontent.com/203209/154560241-9e37e0ab-7d60-43c3-9067-80c16c9d2238.png)
Aleph Desktop version 2.6.4
Windows 10

Previous versions work fine.

**Comment by keyonchristain** [comment]
same on MacOS

**Comment by monneyboi** [comment]
Same on Linux

I have this problem with both the released builds and when building manually with `make install` & `make dev`/`make build`.

Running `npm install` instead of `make install` to skip linking`react-ftm`, and running `make dev` after resulted in a dev build that rendered the main interface, but still does not load or save. Running `make build` results in a build that still does not render.

**Comment by agonzalezQk** [comment]
I have the same issue, does anyone know a solution?
